version: 1
labels:
  - label: "ğŸ’» aspect: code"
    color: "#04338c"

  - label: "Completed âœ…"
    color: "#048F10"

  - label: "fix"
    color: "#9FC6CF"

  - label: "âœ¨ goal: improvement"
    color: "#ffffff"

  - label: "â­ goal: addition"
    color: "#ffffff"

  - label: "ğŸŸ¨ priority: medium"
    color: "#ffcc00"
